# GitHub Secret Scanning Custom Patterns
# This file defines custom patterns to detect secrets specific to this project
# See: https://docs.github.com/en/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning

# Azure Functions keys typically follow this pattern:
# - Base64 encoded strings
# - Often 64+ characters long
# - Used with x-functions-key header

# Note: GitHub's built-in secret scanning already detects many Azure secrets
# This configuration provides additional project-specific patterns

# Pattern to detect Azure Functions keys in code, documentation, or curl commands
# Examples:
# - curl -H "x-functions-key: <key>"
# - x-functions-key: <key>
# - Authorization: <key>

# To enable custom secret scanning:
# 1. Go to repository Settings → Security → Code security and analysis
# 2. Enable "Secret scanning"
# 3. Enable "Push protection" to prevent secrets from being committed
# 4. Custom patterns can be added via Settings → Security → Secret scanning → Custom patterns
